// Map of feature IDs to their toggle functions
import { FeatureID } from "./definitions"
import {
	hideBrowseButton,
	hideDotsButton,
	hideFollowingButton,
	hideNotificationsButton,
	hidePrimeGamingButton,
	hideTopBitsButton,
	hideTopTurboButton,
	hideWhispersButton,
	toggleAlwaysCloseAdblockPopup,
	toggleAutoManageChatWebSocket,
	toggleBelowVideoAdSection,
	toggleChatBadges,
	toggleChatClipBestMoments,
	toggleChatGrayscale,
	toggleChatMonetizationButtons,
	toggleComboButton,
	toggleCommunityHighlightStack,
	toggleFeaturedStreamPlayByDefault,
	toggleInfoAboutSection,
	toggleInfoChannelPanelSection,
	toggleInfoMonetizationButtons,
	toggleInfoMonthlyRecap,
	toggleInfoSectionGrayscale,
	toggleInfoViralClipSection,
	toggleLeftSidebar,
	toggleLeftSidebarAlwaysShowMore,
	toggleLeftSidebarFollowedChannels,
	toggleLeftSidebarLiveChannels,
	toggleLeftSidebarOfflineChannels,
	toggleLeftSidebarRecommendedCategories,
	toggleLeftSidebarStories,
	toggleLeftSidebarViewersAlsoWatch,
	toggleLeftSidebarViewership,
	toggleSideNavGrayscale,
	toggleStickyFooter,
	toggleThumbnailViewership,
	toggleTopBarGrayscale,
	toggleTopGifters,
	toggleVideoAdWrapper,
	toggleVideoGiftButtonSection,
	toggleVideoGrayscale,
	toggleVideoViewership,
} from "./domManipulators"

export const featureToggleMap: Record<FeatureID, (enabled: boolean) => void> = {
	no_chat: () => {},
	test_mode: () => {},
	grayscale_all: () => {},
	blocked_categories: () => {},
	blocked_channels: () => {},
	simple_mode_preset: () => {},
	is_simple_mode: () => {},
	hide_info: () => {},
	hide_topbar: () => {},
	hide_video_section: () => {},
	no_chat_section: () => {},
	extension_enabled: () => {},
	other_section: () => {},
	hide_chat_badges: (value: boolean) => toggleChatBadges(value),
	toggle_topbar_grayscale: (value: boolean) => toggleTopBarGrayscale(value),
	hide_topbar_following_button: (value: boolean) => hideFollowingButton(value),
	hide_topbar_browse_button: (value: boolean) => hideBrowseButton(value),
	hide_topbar_dots_button: (value: boolean) => hideDotsButton(value),
	hide_prime_gaming_button: (value: boolean) => hidePrimeGamingButton(value),
	hide_notifications_button: (value: boolean) => hideNotificationsButton(value),
	hide_whispers_button: (value: boolean) => hideWhispersButton(value),
	hide_top_bits_button: (value: boolean) => hideTopBitsButton(value),
	hide_top_turbo_button: (value: boolean) => hideTopTurboButton(value),
	hide_left_sidebar: (value: boolean) => toggleLeftSidebar(value),
	toggle_sidenav_grayscale: (value: boolean) => toggleSideNavGrayscale(value),
	hide_left_sidebar_stories: (value: boolean) => {
		toggleLeftSidebarStories(value)
		// toggleLeftSidebarStoriesXS(value)
	},
	hide_thumbnail_viewership: (value: boolean) => toggleThumbnailViewership(value),
	hide_video_viewership: (value: boolean) => toggleVideoViewership(value),
	hide_left_sidebar_viewership: (value: boolean) => toggleLeftSidebarViewership(value),
	hide_left_sidebar_followed_channels: (value: boolean) => toggleLeftSidebarFollowedChannels(value),
	hide_left_sidebar_offline_channels: (value: boolean) => toggleLeftSidebarOfflineChannels(value),
	hide_left_sidebar_live_channels: (value: boolean) => toggleLeftSidebarLiveChannels(value),
	hide_left_sidebar_viewers_also_watch: (value: boolean) =>
		toggleLeftSidebarViewersAlsoWatch(value),
	hide_left_sidebar_recommended_categories: (value: boolean) =>
		toggleLeftSidebarRecommendedCategories(value),
	left_sidebar_always_show_more: (value: boolean) => toggleLeftSidebarAlwaysShowMore(value),
	hide_chat_monetization: (value: boolean) => toggleChatMonetizationButtons(value),
	hide_top_gifters: (value: boolean) => toggleTopGifters(value),
	hide_chat_highlights: (value: boolean) => toggleCommunityHighlightStack(value),
	toggle_chat_grayscale: (value: boolean) => toggleChatGrayscale(value),
	hide_chat_clip_best_moments: (value: boolean) => toggleChatClipBestMoments(value),
	featured_stream_play_by_default: (value: boolean) => toggleFeaturedStreamPlayByDefault(value),
	toggle_video_grayscale: (value: boolean) => toggleVideoGrayscale(value),
	hide_video_gift_section: (value: boolean) => toggleVideoGiftButtonSection(value),
	hide_video_ad_wrapper: (value: boolean) => {
		toggleVideoAdWrapper(value)
		toggleBelowVideoAdSection(value)
	},
	always_close_adblock_popup: (value: boolean) => {
		toggleAlwaysCloseAdblockPopup(value)
	},
	toggle_info_grayscale: (value: boolean) => toggleInfoSectionGrayscale(value),
	hide_info_monetization_buttons: (value: boolean) => toggleInfoMonetizationButtons(value),
	hide_combo_button: (value: boolean) => toggleComboButton(value),
	hide_info_viral_clip_section: (value: boolean) => toggleInfoViralClipSection(value),
	hide_info_monthly_recap: (value: boolean) => toggleInfoMonthlyRecap(value),
	hide_info_about_section: (value: boolean) => toggleInfoAboutSection(value),
	hide_info_channel_panel_section: (value: boolean) => toggleInfoChannelPanelSection(value),
	hide_sticky_footer: (value: boolean) => toggleStickyFooter(value),
	auto_manage_chat_websocket: (value: boolean) => toggleAutoManageChatWebSocket(value),
}
